### PR TITLE
Finish Iteration2 service part implementation

### PR DESCRIPTION
**Pull request by Alex-XJK**
Add support for Employee's salary, position, and performance.
Implemented functions, added endpoints, created tests, and wrote documents for those new features.
Rename and unify endpoint names.

### CODE REVIEW

**Comment by Alex-XJK** [comment]
@phoebeww I changed some of your previously developed endpoints, just for your information.

**Comment by Alex-XJK** [comment]
@tonyxyu As discussed, currently, it can pass all the tests that do not involve the real database and achieve 74% branch coverage.
image
However, the `HrDatabaseFacade.updateEmployee()` is currently just a dummy function that needs to be implemented.
We also need to re-deploy the database and do the debugging so that those three `DatabaseConnectionTest` can get passed. Only after this can this PR get merged.

**Review by tonyxyu — APPROVED** [review]
Looks great! I will work on the backend from here.

**Comment by Alex-XJK** [comment]
@tonyxyu TODO: double-check and improve db-related tests.
I am not quite familiar with `JUnit.Assume`. Because our database is down now, I can only make sure my technique works well to skip DB tests when the connection fails, but I cannot test whether it can do the test once the DB connection is recovered. 
Please do the `mvn test` again after you re-construct our new DB, and update the connection parameters. This time, the JUnit test should NOT skip any test cases, and the branch coverage should be above 75%. If it still skips those 3 tests, please let me know.

**Pull request merged**
